services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: weight-tracker-backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: production
      PORT: 4000
    ports:
      - "4000:4000"
    networks:
      - weight-tracker-network
    volumes:
      - ./prisma:/app/prisma
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:4000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend (React + Nginx)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weight-tracker-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - weight-tracker-network
    restart: unless-stopped

  # Nginx Reverse Proxy (Optional - for production)
  nginx-proxy:
    image: nginx:alpine
    container_name: weight-tracker-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - weight-tracker-network
    profiles:
      - production

networks:
  weight-tracker-network:
    driver: bridge
