[phases.setup]
nixPkgs = ["nodejs", "pnpm", "postgresql"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx prisma migrate deploy"
]

[start]
cmd = "pnpm run start" 